name: evox
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1

  riverpod: ^2.4.6
  flutter_riverpod: ^2.4.6

  shared_preferences: ^2.2.2
  dio: ^5.3.3
  flutter_svg: ^2.0.9
  json_annotation: ^4.8.1

  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.0
  octo_image: ^2.0.0
  url_launcher: ^6.2.1
  shimmer: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  video_player: ^2.8.1

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/ep.png"
    min_sdk_android: 21



flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 300
